# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 200000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"


# --- Adversarial / Robustness Parameters ---
adv_mode: "none"        # 默认模式: "none", "random", "rarl", "rap"
adv_pop_size: 2         # RAP 模式下的攻击者种群数量
adv_attack_prob: 0.1    # 攻击概率 (epsilon)
adv_switch_ep_freq: 5000  # RARL/RAP 交替训练的频率
adv_max_attacks_per_episode: 4  # 每个 episode 最多攻击 4 次
adv_max_agents_per_attack: 2     # 每次攻击最多干扰 1 个智能体
adv_method: "budget_ppo"  # [新增] dqn, budget_ppo
adv_max_attack_budget: 4 # [新增] PPO 模式下的预算


# --- Pretrained Model ---
pretrained_path: ""  # 设置为你的模型文件夹路径，例如 "results/models/3m_qmix_seed1"
# adv_pretrained_path: "/home/data/sdb5/jiangjunyong/H_MARL/WALL-main/src/latest_model.pth"  # 设置为你的预训练攻击者模型路径，例如 "results/adv_models/3m_budget_ppo_seed1/latest_model.pth"

# --- Adversarial Control ---
train_victim: True  # 默认训练 Victim。设为 False 则固定 Victim。
adv_ppo_batch_size: 40
adv_paths: ""
save_path: ""
budgetppo_selection_mode: "model"
budgetppo_action_mode: "model"
heuristic_attack_prob: 0.4